# Minecraft 26.2 is unobfuscated, so no remapping is required
modstitch.platform=fabric-loom

# Global
deps.fabric_loader=0.19.3
deps.flk=1.13.13
deps.flk_kotlin=kotlin.2.4.10
deps.yacl=3.9.6+26.2-fabric
deps.arch_api=21.0.7

# Fabric
deps.fapi=0.156.0+26.2
deps.modmenu=20.0.1
deps.dabr=3.8.4+26.2-fabric

# Mod
mod.mc_version_range=26.2
mod.mc_title=26.2
mod.mc_targets=26.2
